{ config, lib, pkgs, ... }:

let
  # rebuild.sh symlinks the repo to ~/.configs, so this path is stable on any
  # machine that bootstraps with it. mkOutOfStoreSymlink links straight at the
  # repo rather than copying into the nix store, so edits to the files below
  # take effect on save instead of needing a rebuild.
  dotfiles = "${config.home.homeDirectory}/.configs";
  link = path: config.lib.file.mkOutOfStoreSymlink "${dotfiles}/${path}";
in
{
  home.username = "sph";
  home.homeDirectory = "/Users/sph";
  home.stateVersion = "26.05";

  programs.home-manager.enable = true;

  home.packages = with pkgs; [
    # --- core CLI ----------------------------------------------------------
    # neovim is a plain package, not programs.neovim: that module generates its
    # own init.lua, which would collide with the hand-managed nvim/ below.
    neovim
    jq
    eza
    tmux
    zoxide
    starship

    # --- GNU userland ------------------------------------------------------
    # coreutils-prefixed installs gls/gcat/gdate/... exactly like Homebrew's
    # keg-only coreutils did. Plain `coreutils` would install them UNPREFIXED
    # and shadow the macOS versions on PATH.
    coreutils-prefixed
    gawk
    gnumake

    # Unprefixed in nixpkgs, so these SHADOW the BSD versions in /usr/bin.
    # Uncomment only if you want GNU sed/grep/tar/find as the default.
    # gnused
    # gnugrep
    # gnutar
    # findutils

    # --- dev ---------------------------------------------------------------
    git
    gh
    go
    golangci-lint

    # Replaces nvm, which was pinned to node v18.1.0 (EOL April 2023) and was
    # never sourced from the shell config -- it only reached PATH by leftover.
    nodejs

    # --- python --------------------------------------------------------------
    # Global interpreter for scripting only. Per-project environments come from
    # uv, which UV_PYTHON_PREFERENCE pins to this interpreter.
    python3
    uv
    ruff
    mypy
    black

    # --- google cloud --------------------------------------------------------
    # Replaces the gcloud-cli Homebrew cask, which was the sole reason brew's
    # python@3.14 (and its eight dependencies) stayed installed.
    # Trade-off: `gcloud components update` cannot work against the read-only
    # nix store. Update by bumping nixpkgs instead.
    (google-cloud-sdk.withExtraComponents [
      google-cloud-sdk.components.gke-gcloud-auth-plugin
    ])

    # --- containers / kubernetes -------------------------------------------
    # CLI only, no daemon. Previously this came from OrbStack.app via a symlink
    # at /usr/local/bin/docker; it talks to whatever context is active (today
    # Docker Desktop). Desktop's plugins in ~/.docker/cli-plugins still work.
    docker-client
    kubernetes-helm
    kind
    cilium-cli

    # --- network -----------------------------------------------------------
    wireshark-cli # tshark/dumpcap; the GUI stays a cask (needs ChmodBPF)

    # --- misc --------------------------------------------------------------
    gemini-cli
    nethack
  ];

  # --- zsh -----------------------------------------------------------------
  # Generated by home-manager rather than hand-linked. That removes the
  # duplicated Homebrew init that used to live in both .zprofile and .zshrc,
  # and lets the plugins come from the store directly instead of relying on
  # the per-user profile layout.
  programs.zsh = {
    enable = true;
    enableCompletion = true;
    autosuggestion.enable = true;
    syntaxHighlighting.enable = true;

    history = {
      size = 50000;
      save = 50000;
      path = "${config.home.homeDirectory}/.zsh_history";
      share = true;
      append = true;
      ignoreDups = true;
      ignoreSpace = true;
    };

    oh-my-zsh = {
      enable = true;
      theme = "robbyrussell";
      # Keep this list short -- each plugin is sourced on every shell start.
      plugins = [ "git" "docker" "kubectl" ];
    };

    shellAliases = {
      ".." = "cd ..";
      "..." = "cd ../..";
      ll = "ls -lah";
      c = "clear";

      gs = "git status";
      gd = "git diff";
      gl = "git log --oneline --graph --decorate";
      gcm = "git commit -m";
      gp = "git push";

      # .zshrc is generated now, so point these at the files you can edit.
      zconf = "$EDITOR ~/.config/zsh/local.zsh";
      nixconf = "$EDITOR ~/.config/home-manager/home.nix";
      zreload = "exec zsh";
    };

    sessionVariables = {
      EDITOR = "code --wait";
      GOPATH = "${config.home.homeDirectory}/go";
      working_dir = "${config.home.homeDirectory}/go/src/k8s.io";
      user = "shaunhickson";
    };

    # Read by every zsh, interactive or not.
    envExtra = ''
      [ -f "$HOME/.cargo/env" ] && . "$HOME/.cargo/env"
    '';

    initContent = lib.mkMerge [
      (lib.mkBefore ''
        # Homebrew sets HOMEBREW_PREFIX and prepends /opt/homebrew to PATH.
        if [[ -z "$HOMEBREW_PREFIX" ]]; then
          if [[ -f /opt/homebrew/bin/brew ]]; then
            eval "$(/opt/homebrew/bin/brew shellenv)"
          elif [[ -f /usr/local/bin/brew ]]; then
            eval "$(/usr/local/bin/brew shellenv)"
          fi
        fi

        # Put nix back ahead of Homebrew, then append the lower-precedence
        # dirs. typeset -U keeps the leftmost occurrence of each entry.
        path=(
          "$HOME/.antigravity/antigravity/bin"
          "$HOME/.nix-profile/bin"
          "/etc/profiles/per-user/$USER/bin"
          /run/current-system/sw/bin
          /nix/var/nix/profiles/default/bin
          $path
        )
        path+=( "$HOME/go/bin" "$HOME/.local/bin" )
        typeset -U path PATH
      '')
      (lib.mkAfter ''
        setopt HIST_VERIFY

        # Machine-local and experimental tweaks. ~/.config is this repo, so
        # this file is zsh/local.zsh -- edit it and reload, no rebuild.
        [[ -f "$HOME/.config/zsh/local.zsh" ]] && source "$HOME/.config/zsh/local.zsh"
      '')
    ];
  };

  programs.zoxide = {
    enable = true;
    enableZshIntegration = true;
  };

  # NOTE: ~/.config is a symlink to this repo, so everything under it --
  # ghostty/, gh/, nvim/, gcloud/ -- is ALREADY in place and needs no linking.
  # An xdg.configFile entry here would make the repo file a symlink pointing
  # back at itself through ~/.configs, i.e. a symlink loop ("Too many levels of
  # symbolic links"). Only files outside ~/.config belong above.
}
